# Generated by Django 5.2.4 on 2025-07-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_customer_store_custo_last_na_e6a359_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="store_custo_last_na_e6a359_idx",
        ),
        migrations.AlterModelTable(
            name="customer",
            table=None,
        ),
    ]
