name: Django Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL
      run: sleep 20

    - name: Setup database
      run: |
        sudo apt-get install -y mysql-client
        mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE test_db;"
        mysql -h 127.0.0.1 -u root -proot -e "CREATE USER 'test_user'@'%' IDENTIFIED BY 'test_pass';"
        mysql -h 127.0.0.1 -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'%' WITH GRANT OPTION;"
        mysql -h 127.0.0.1 -u root -proot -e "FLUSH PRIVILEGES;"


    - name: Run Django tests
      env:
        DB_NAME: test_db
        DB_USER: test_user
        DB_PASSWORD: test_pass
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        SECRET_KEY: testsecretkey
        DEBUG: 1
      run: python manage.py test playground.tests
